FROM python:3.11 AS builder

WORKDIR /FastApiProject
COPY ../poetry.lock ../pyproject.toml ./
RUN python -m pip install --no-cache-dir poetry==1.8.2 \
    && poetry config virtualenvs.in-project true \
    && poetry install --only main --no-interaction --no-ansi

FROM python:3.11-slim

WORKDIR /FastApiProject
COPY --from=builder /FastApiProject ./
COPY web_app.py ./
COPY static ./
COPY templates ./

CMD ["./.venv/bin/uvicorn", "web_app", "--host", "0.0.0.0", "--port", "5000"]